export const Strings = {
  appTitle: "My Tasks",
  addTask: "Add Task",
  enterTask: "Enter a new task...",
  noTasks: "No tasks yet. Add one to get started!",
  taskAdded: "Task added successfully!",
  taskCompleted: "Task completed!",
  taskDeleted: "Task deleted!",
  deleteTask: "Delete",
  markComplete: "Complete",
  markIncomplete: "Incomplete",
  allTasks: "All Tasks",
  completedTasks: "Completed",
  pendingTasks: "Pending",
  loadingMore: "Loading more tasks...",
  notificationTitle: "Task Reminder",
  notificationBody: "Time to complete: ",
  dataLoaded: "Tasks loaded successfully!",
  dataLoadError: "Failed to load tasks",
  dataSaved: "Tasks saved successfully!",
  dataSaveError: "Failed to save tasks",
  editTask: "Edit Task",
  saveChanges: "Save Changes",
  cancelEdit: "Cancel",
  taskUpdated: "Task updated successfully!",
  LoadingTasks: "Loading tasks...",
};
